<?php

namespace App\Controller\Admin;

use App\Entity\FlashInfo;
use App\Entity\Slide;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\SlugField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class FlashInfoCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return FlashInfo::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Flash info')
            ->setEntityLabelInPlural('Slides')
            ->setPageTitle(Crud::PAGE_INDEX, 'Liste des flash infos')
            ->setPageTitle(Crud::PAGE_EDIT, 'Modifier un flash info')
            ->setPageTitle(Crud::PAGE_NEW, 'Ajouter un flash info')
            ->setPageTitle(Crud::PAGE_DETAIL, 'Consulter un flash info')
            ->setEntityPermission('ROLE_USER')
            ->setDefaultSort(['id' => 'DESC', 'title' => 'ASC', 'datePublished' => 'DESC'])
            ;
    }

    public function createEntity(string $entityFqcn)
    {
        $flashInfo = new FlashInfo();
        $flashInfo->setAuthor($this->getUser());
        $flashInfo->setDatePublished(new \DateTime());
        $flashInfo->setIsVisible(True);
        return $flashInfo;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('title', 'Flash Info'),
            SlugField::new("slug")->setTargetFieldName("title"),
            TextField::new('link', 'Lien'),
            BooleanField::new("isVisible", 'Visible ?'),
            AssociationField::new('author', 'Auteur')->setDisabled(),
            DateTimeField::new('datePublished', 'Date de publication'),
        ];
    }

    public function configureFilters(Filters $filters): Filters
    {
        //return parent::configureFilters($filters); // TODO: Change the autogenerated stub
        return $filters
            ->add('datePublished')
            ->add('author')
            ->add('isVisible')
            ;
    }
}
