<?php

namespace App\Controller\Admin;

use App\Entity\Post;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\SlugField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Bundle\MakerBundle\Doctrine\RelationManyToOne;

class PostCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Post::class;
    }

    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Article')
            ->setEntityLabelInPlural('Articles')
            ->setPageTitle(Crud::PAGE_INDEX, 'Liste des articles')
            ->setPageTitle(Crud::PAGE_EDIT, 'Modifier un article')
            ->setPageTitle(Crud::PAGE_NEW, 'Ajouter un article')
            ->setPageTitle(Crud::PAGE_DETAIL, 'Consulter un article')
            ->setEntityPermission('ROLE_USER')
            ->setDefaultSort(['id' => 'DESC'])
            ->setDefaultSort(['id' => 'DESC', 'title' => 'ASC', 'datePublished' => 'DESC'])
            ;
    }

    public function createEntity(string $entityFqcn)
    {
        $post = new Post();
        $post->setAuthor($this->getUser());
        $post->setDatePublished(new \DateTime());
        $post->setIsVisible(True);
        return $post;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('title', 'Titre'),
            SlugField::new("slug")->setTargetFieldName("title"),
            ImageField::new("imagePost", 'Image')
                ->setBasePath('assets/uploads/posts')
                ->setUploadDir('public/assets/uploads/posts')
                ->setUploadedFileNamePattern('[randomhash].[extension]')
                ->setRequired(false),
            TextEditorField::new('content', 'Contenu'),
            BooleanField::new("isVisible", 'Visible ?'),
            AssociationField::new('author', 'Auteur')->setDisabled(),
            DateTimeField::new('datePublished', 'Date de publication'),
        ];
    }

    public function configureFilters(Filters $filters): Filters
    {
        //return parent::configureFilters($filters); // TODO: Change the autogenerated stub
        return $filters
            ->add('title')
            ->add('datePublished')
            ->add('author')
            ->add('isVisible')
            ;
    }


}
