<?php

namespace App\Controller\Admin;

use App\Entity\Post;
use App\Entity\Slide;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Config\Filters;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\SlugField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class SlideCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Slide::class;
    }


    public function configureCrud(Crud $crud): Crud
    {
        return $crud
            ->setEntityLabelInSingular('Slide')
            ->setEntityLabelInPlural('Slides')
            ->setPageTitle(Crud::PAGE_INDEX, 'Liste des slides')
            ->setPageTitle(Crud::PAGE_EDIT, 'Modifier un slide')
            ->setPageTitle(Crud::PAGE_NEW, 'Ajouter un slide')
            ->setPageTitle(Crud::PAGE_DETAIL, 'Consulter un slide')
            ->setEntityPermission('ROLE_USER')
            ->setDefaultSort(['id' => 'DESC', 'title' => 'ASC', 'datePublished' => 'DESC'])
            ;
    }

    public function createEntity(string $entityFqcn)
    {
        $slide = new Slide();
        $slide->setAuthor($this->getUser());
        $slide->setDatePublished(new \DateTime());
        $slide->setIsVisible(True);
        return $slide;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            TextField::new('title', 'Titre'),
            SlugField::new("slug")->setTargetFieldName("title"),
            TextField::new('subTitle', 'Description'),
            TextField::new('subTitle2', 'Chapeau (Facultatif)'),
            ImageField::new("imageSlide", 'Image')
                ->setBasePath('assets/uploads/slides')
                ->setUploadDir('public/assets/uploads/slides')
                ->setUploadedFileNamePattern('[randomhash].[extension]')
                ->setRequired(false),
            TextField::new('slidePosition', 'Alignement du slide "centred" ou vide'),
            TextField::new('link', 'Lien'),
            TextField::new('buttonText1', 'Bouton 1'),
            TextField::new('buttonLink1', 'Lien Bouton 1'),
            TextField::new('buttonText2', 'Bouton 2'),
            TextField::new('buttonLink2', 'Lien Bouton 2'),
            BooleanField::new("isVisible", 'Visible ?'),
            AssociationField::new('author', 'Auteur')->setDisabled(),
            DateTimeField::new('datePublished', 'Date de publication'),
        ];
    }

    public function configureFilters(Filters $filters): Filters
    {
        //return parent::configureFilters($filters); // TODO: Change the autogenerated stub
        return $filters
            ->add('datePublished')
            ->add('author')
            ->add('isVisible')
            ;
    }


}
